# Generated by Django 3.1.13 on 2021-10-23 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(error_messages={'unique': 'A user with this email already exists.'}, max_length=254, unique=True, verbose_name='email address')),
                ('driving_licence', models.CharField(max_length=20)),
                ('ip_address', models.GenericIPAddressField(protocol='IPv4')),
                ('city', models.CharField(max_length=50)),
            ],
        ),
    ]
